### ISSUE TITLE
Distance between toasts

### ISSUE THREAD

**Issue by Reached** [ZitRos/toaster-js#2]
Hi there,

Great library, small and lean and easy to use :).

However how can I adjust the distance between each individual toast? Right now they are bunking up against each other, I cannot find anywhere in the docs about this, only the `topOrigin` setting, can you help here? :)

**Comment by nikitaeverywhere** [comment]
Hi Reached!

Glad to hear you liked toaster-js! To achieve what you want just add some CSS, for example:

```css
.toast > .body {
  margin: 0 5px 5px 5px;
}
```

Cheers!

**Comment by Reached** [comment]
So obvious to put it on the body instead of directly on the toast-parent 👍 

Thank you :)!
