### ISSUE TITLE
How to destroy toaster manually using js code?

### ISSUE THREAD

**Issue by PratibhaP** [ZitRos/toaster-js#3]

**Comment by nikitaeverywhere** [comment]
Hello Pratibha!

Do you mean to completely vanish all toasts and un-bind any bindings of ToasterJS?

If so, currently there is no such thing. But it can easily be implemented even today, just let me know.

**Comment by PratibhaP** [comment]
Yes exactly, I wanted to destroy previously created last one toaster or all.

**Comment by nikitaeverywhere** [comment]
Okay, give me a moment. I’ll notify you once it’s done!

**Comment by nikitaeverywhere** [comment]
Done! I've published version `2.0.1`, as I decided to do major update on styles. Now, Toaster-JS assigns CSS styles instead of hard-coded `opacity`. [Check this out!](https://zitros.github.io/toaster-js/)

Regarding to deleting Toast messages, use this:

```js
const toast = new Toast("Hello!");

toast.delete();
```

Please let me know if that's what you expected. Or maybe you need something like `deleteAll`?

**Comment by nikitaeverywhere** [comment]
Nevermind, `2.1.0` now has this function. Usage:

```javascript
import { Toast, deleteAllToasts } from "toaster-js";

const toast = new Toast("Hello!");

toast.delete(); /* OR */ deleteAllToasts();
```

**Comment by PratibhaP** [comment]
Using deleteAllToasts() method, I can delete all previously created toastr. 
Need to download again toaster-js.
Thank you for quick reply and solution @ZitRos

**Comment by nikitaeverywhere** [comment]
Thank you! Yes you need to download it again :)

I am also working on #4 right now, check this out. Maybe you'll find it useful.

So I am closing this issue as it is resolved. I would also appreciate if you star Toaster-JS repository here on GitHub, this will show me that I am doing something useful for people 😃 Thank you!

**Comment by PratibhaP** [comment]
Yes, definitely
