### ISSUE TITLE
Infinite display

### ISSUE THREAD

**Issue by heshhassan** [ZitRos/toaster-js#5]
Is there way to pass value to the time parameter that shows the toast message for infinite?

**Comment by nikitaeverywhere** [comment]
Hello!
Yep, the third parameter in Toast constructor is actually time in milliseconds of how long the toast stays on the screen. You can pass something like `99999999` there to make it stay “for a long long time”. Note that it uses setTimeout internally, and if I’m not mistaking it has some ceil timeout value like 2^32.
Hope this helps!
P.S. If you want to set a particular timeout as a default, you are welcome to submit a pull request with that feature!

**Comment by nikitaeverywhere** [comment]
@HeshamElghndour any updates? Did it help?

**Comment by heshhassan** [comment]
Yep, I used the long timeout mseconds. Thanks a lot :)

**Comment by nikitaeverywhere** [comment]
Good!
