### ISSUE TITLE
What is the canonical way to position toasts horizontally? 

### ISSUE THREAD

**Issue by hipitihop** [ZitRos/toaster-js#6]
I see this project hasn't had any recent love. I hope it is being maintained. I'm writing a module for MagicMirror which uses toasts, and needs to be able to specify arbitrary HTML content, I'm hoping to be able to even use chart.js within toasts.

The `topOrigin` option allows some control along the Y axis, how do you recommend being able to place toasts horizontally in the centre or left part of the screen?

**Comment by nikitaeverywhere** [comment]
Hello! Thanks for coming! Yes it's being maintained, it wasn't just getting any issues lately.

1. Adding a feature of being able to move toasts to the left / top corners sound good to me! Needs to be added though. I think it's not that complex. In the center of the screen - sounds interesting but I can also see the use case of it. Would adding options like `alighHorisontal = 'left'|'center'|'right'` and possibly `alignVertical` (maybe later) work for you? (global setting)

Regarding passing arbitrary HTML, you can already do it:

```
const element = document.createElement("div");
element.innerHTML = "Whatever you want";
const newToast = new Toast(element, Toast.TYPE_MESSAGE);
```

**Comment by hipitihop** [comment]
@ZitRos  Thanks for the reply. I'm glad to hear it is being maintained. I guess I'm just conditioned when you don't see issues or any code checkin for over two years you worry the project has died :-)

I read your docs again and indeed I see I'm able to use any HTML. This makes your lib stand out from [this list](https://www.cssscript.com/best-toast-notification-libraries/) for my use case.

I also notice and started to experiment with just overriding your default.css to position the toasts and I have managed to center screen snipped below. It would certainly be more convenient to be able to pass parameters to each toast.  You might want to consider specifying both the horizontal and vertical by symbolic regions of the screen e.g. `position: "top-left"` or `position: "bottom-right"

Here is my centered
![image](https://user-images.githubusercontent.com/4626024/81355660-82e97c00-9112-11ea-814a-095b6aed00ee.png)

Rather then hanging on to instances of toasts in my JS code, it would be nice to be able to give toasts an optional `id` and use that in the API, this way, if I provide new content for a toast `id` that is already on screen (in the DOM), it replaces it, not create a new toast. Then one could close individual toasts. Anyway some ideas I have seen implemented in other libs.

**Some more context:**
I'm writing a module for [MagicMirror²](https://github.com/MichMich/MagicMirror)
MagicMirror uses a similar concept for positioning modules. In my case, my module won't have a specific position as such and will have some longer lived toasts to be in the center of the screen, while other types may slide in and out from screen edges.

**Comment by nikitaeverywhere** [comment]
Cool thing, thanks for sharing!

So the original idea of this library was to have an easy way of producing toasts, and I support it being extended to some extent. As far as you noticed, toasts stick to each other. There is a mechanism that controls their appearance and animations (say, you can produce a 1-minute long toast and then 5-second long toast, and the old ones will be animated down again once the 5-second one collapses). This can't make specifying positions of each individual toasts as per original idea. But if you're looking to have a position for a group of toasts then it's possible and I support being able to configure that - can be implemented! I don't understand your "center" though. Is it center or center + some pixels?

Regarding having a close button: though it's not documented (hmm, why) I think you can simply achieve it with 

```js
const createCustomToast = (html = 'no message') => {
  const content = document.createElement("span");
  const closeButton = document.createElement("button");
  const element = document.createElement("div");

  content.innerHTML = html;
  element.appendChild(content);  
  element.appendChild(closeButton);

  const newToast = new Toast(element, Toast.TYPE_MESSAGE);
  closeButton.addEventListener('click', () => newToast.delete());
};

createCustomToast('Hello!');
```

I don't see adding IDs to the library itself as a way to go, this will start inflating this module with something unnecessary. Manipulating with javascript instances is much easier, and if you need IDs you can simply implement them yourself (extending the example above):

```js
const toasts = new Map();
let nextToastId = 1;

export const createCustomToast = (html = 'no message') => {
  const content = document.createElement("span");
  const closeButton = document.createElement("button");
  const element = document.createElement("div");

  content.innerHTML = html;
  element.appendChild(content);  
  element.appendChild(closeButton);

  const newToast = new Toast(element, Toast.TYPE_MESSAGE);
  toasts.add(nextToastId++, newToast)
  closeButton.addEventListener('click', () => newToast.delete());
};

export const deleteCustomToast = (id) => {
  if (toasts.has(id)) {
    toasts.get(id).delete();
    taasts.delete(id);
  }
}
```

Here you go with your custom wrapper module for a toasts library. I would generally recommend making wrappers if you f.e. would like to replace the library one day - thus you won't have a hard dependency across the whole codebase.

Note I didn't run the above code and it may contain typos; however, if it works straight away let me know - I'll bake myself a cake. Hope this helps! :)

Let me know your thoughts: I can implement positioning (global) this weekend I think.

**Comment by hipitihop** [comment]
Thanks for the examples, I'm not sure I asked about a close button, but as you say there is a fair bit I can achieve using wrappers, so it is food for thought.
I certainly don't want to push your library away from it's origins either. I need to think though my usecases a little further before you do any work.

- regarding `center` position, if you look at "center-top" or "center-bottom" in [this magic mirror regions](https://forum.magicmirror.builders/topic/286/regions), the blue ones, my module div is  defined within one of these positions. *note: magic mirror supports multiple instances of a module being defined, each could be defined in same or another region. If multiple instances are defined in the same region, they are just stacked within that area.* So my module defines the container/parent div within which 0-n toasts will be shown. So the best way to set this up is for my module div to decide which region on screen it lives, and all toasts are relative to that. That way, I could define 2 modules in MagicMirror, e.g. one that shows toasts "top-center" and another module defined "bottom-right" which shows different styled toasts there.

- regarding id's, yes I can manage my own registry with my module JS. But I was also thinking that if I define an `id` div attribute when creating the toast, then at anytime my JS could also just retrieve the instance via `getElementById()` assuming I know what id I'm after. Based on your comments regarding wrappers, I can probably achieve that too by wrappers.

So I'm guessing that the only thing at this point is for me to work out the correct CSS instead of your default, so that toasts show relative to my module container div position, as opposed to always right of screen or some such.

**Comment by nikitaeverywhere** [comment]
Right, it's just CSS. We can define something like "anchor element" globally though (by default - body) if you need to stick to a specific element, but that's the matter of CSS as well, just shipped with the library redefining some styles (the same applies for left/right positions). Sticking to top, however, requires some JS rethinking.

**Comment by nikitaeverywhere** [comment]
Please let me know if you'd like positioning to be implemented on the library level to avoid playing with CSS.

**Comment by hipitihop** [comment]
@ZitRos thanks. I'm still implementing and experimenting a very specific use case where I popup timers, each as a toast with a chart.js doughnut, all stacked top center of screen. My requirements are not yet clear as I have not tested a separate module/region, so I'm a little reticent for you to do unnecessary work. I'm suspecting that if I get the CSS override correct, it may work within any MM module/region and I won't need per toast properties. For the specific timer case, I will also want to size the toast components based on how many are currently running i.e. if only 1 or 2  then some max width/height, if more, then next size down, although a toast may start one size, and be reduced/increased as toasts are added/removed. I suspect all this will also need to be done via my JS and wrappers.

One feature that is probably a more concrete requirement is to optionally allow the toasts to be `shown/stacked horizontally` with another setting for the maximum number of toast per row e.g. 2. If more then the row max of toasts, then spill on to next row. e.g. below is 1 timer, if I add another, it would appear next to this one to it's right, a third would flow onto next row, so show below the first timer. etc.

Progress:
![image](https://user-images.githubusercontent.com/4626024/81761165-975fb700-950c-11ea-9ba6-4d807a717c61.png)

**Comment by nikitaeverywhere** [comment]
Hmm, the latter one sounds super-specific. I wouldn't even call it a "Toast" anymore.

Okay, come back once you know the exact things you will need from the library! Thanks!

**Comment by nikitaeverywhere** [comment]
Any updates? Otherwise feel free just to close this issue.

**Comment by hipitihop** [comment]
Thanks @ZitRos appoligies for tardiness. I'm happy with the current functionality and I agree my use case was very specific. Closing.

**Comment by nikitaeverywhere** [comment]
Thanks! If you have other questions or requests - let me know.

Have a good day!
